# Generated by Django 5.0.7 on 2025-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='static/')),
            ],
        ),
    ]
