# Generated by Django 5.0.7 on 2025-06-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0003_alter_statusbar_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusbar',
            old_name='des',
            new_name='Des',
        ),
        migrations.RenameField(
            model_name='statusbar',
            old_name='img',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='statusbar',
            old_name='name',
            new_name='Name',
        ),
    ]
