# Generated by Django 5.0.7 on 2025-06-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0004_rename_des_statusbar_des_rename_img_statusbar_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='qizzapp.statusbar')),
            ],
        ),
    ]
