# Generated by Django 5.0.7 on 2025-06-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0006_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='option',
        ),
    ]
