# Generated by Django 5.0.7 on 2025-06-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0007_delete_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qizzapp.quizz')),
            ],
        ),
    ]
