# Generated by Django 5.0.7 on 2025-06-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0008_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='qizzapp.quizz'),
        ),
    ]
