# Generated by Django 5.0.7 on 2025-06-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0009_alter_options_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='options',
            new_name='Option',
        ),
    ]
