# Generated by Django 5.0.7 on 2025-06-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0010_rename_options_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='options',
            new_name='quiz',
        ),
    ]
