# Generated by Django 5.0.7 on 2025-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0011_rename_options_option_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('ad_password', models.CharField(max_length=50)),
            ],
        ),
    ]
