# Generated by Django 5.0.7 on 2025-06-08 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0012_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='quiz_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
