# Generated by Django 5.0.7 on 2025-06-08 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0013_admin_quiz_mark_admin_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='quiz_mark',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='time',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='quiz_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
