# Generated by Django 5.0.7 on 2025-06-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0014_remove_admin_quiz_mark_remove_admin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='quiz_mark',
            field=models.FloatField(default=0),
        ),
    ]
