# Generated by Django 5.0.7 on 2025-06-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0015_alter_userlogin_quiz_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
