# Generated by Django 5.0.7 on 2025-06-09 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qizzapp', '0016_alter_userlogin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qizzapp.statusbar'),
        ),
    ]
